export const SET_AUTH = 'SET_AUTH'
export const SET_SIGN_UP = 'SET_SIGN_UP'
export const SET_DATA = 'SET_DATA'
export const SET_USER = 'SET_USER'
export const LOGOUT = 'LOGOUT'
export const RESET_STATE = 'RESET_STATE'
export const NOTIFICATION = 'NOTIFICATION'
export const NOTIFICATION_SERVER_ERROR = 'NOTIFICATION_SERVER_ERROR'
